services:
  sonarr-hd:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-hd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - /mnt/appdata/sonarr-hd:/config
      - /mnt/media/tv/1080p/:/mnt/media/tv/1080p
      - /mnt/media/usenet/:/mnt/media/usenet
      - /mnt/media/torrents/:/mnt/media/torrents
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - shared

  sonarr-uhd:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-uhd
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 8990:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - /mnt/appdata/sonarr-uhd:/config
      - /mnt/media/tv/4k/:/mnt/media/tv/4k
      - /mnt/media/usenet/:/mnt/media/usenet
      - /mnt/media/torrents/:/mnt/media/torrents
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - shared

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 8991:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - /mnt/appdata/sonarr-anime:/config
      - /mnt/media/anime/:/mnt/media/anime
      - /mnt/media/usenet/:/mnt/media/usenet
      - /mnt/media/torrents/:/mnt/media/torrents
    labels:
      - com.centurylinklabs.watchtower.enable=true
    networks:
      - shared

networks:
  shared:
    external: true
