services:
  rdtclient:
    image: rogerfar/rdtclient
    container_name: rdtclient
    restart: unless-stopped
    ports:
      - 6500:6500
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/appdata:/data/db
      - /mnt/media/torrents:/data/downloads
    logging:
       driver: json-file
       options:
          max-size: 10m
    labels:
      - com.centurylinklabs.watchtower.enable=true

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Belgrade
    volumes:
      - /mnt/appdata/sabnzbd:/config
      - /mnt/media/usenet:/mnt/media/usenet
    labels:
      - com.centurylinklabs.watchtower.enable=true

